### PR TITLE
Fixing accessibility

### PR DESCRIPTION
**Pull request by SFarida**
The following points were checked
- page title - One issue found, changed title [here](https://github.com/SFarida/portfolio/pull/7/commits/12db6860799121290450dc4c64f69e383b2e66af#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R8)
- image alt attributes - We made a change [here](https://github.com/SFarida/portfolio/pull/7/commits/92e8475e230a096c12eb68db02fafaae9bf80f12#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L31-R315)  
- headings - No issues found
- Color contrast - One issue found [here](https://github.com/SFarida/portfolio/pull/7/commits/fd781d5df4ccb2f1d5207703c899e7f3352d8517#diff-337cc548d34c6d80b758ad814ddd793a9ec155eb664e127c1fc4d8c5abd19b8aL345-R345)
- Resize - No issues found
- Interaction - No issues found
- Moving content - No issues found
- Multimedia - No issues found
- The basic structure of the page - One issue found - added labels at form element [here ](https://github.com/SFarida/portfolio/pull/7/commits/12db6860799121290450dc4c64f69e383b2e66af#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L336-R346) and [here](https://github.com/SFarida/portfolio/pull/7/commits/12db6860799121290450dc4c64f69e383b2e66af#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L8-R10)

### CODE REVIEW

**Review by anagudelogu — CHANGES_REQUESTED** [review]
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi Team! @SFarida, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 



## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 

## Required Changes ♻️

- [x] I noticed that you didn't change your page title, at the moment, `"portfolio"` is too generic, titles should adequately and briefly describe the content of the page. For example:

* Poor titles:
  * *Microverse project | Your portfolio.*
  * *Portifolio project*
* Better page titles:
  * *Mark's portfolio*
  * *Mark full-stack web developer*

Please consider applying this suggestion! 🤓 🛠️ 


- [x] I suggest that In order to improve further the accessibility of your page you modify the labels of the required fields of your contact form as explained below.

Following the [Easy Checks](https://www.w3.org/WAI/test-evaluate/preliminary/#forms) accessibility instructions for forms:

image

https://github.com/SFarida/portfolio/blob/fd781d5df4ccb2f1d5207703c899e7f3352d8517/index.html#L335-L357

Please add an indicator of which fields are required! 🤓 🛠️ 







_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @SFarida, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

✅ Great use of GitHub flow. 💯
✅ Your project is documented professionally. 📜
✅ Great UI design. 💻

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] You correctly fixed their issues for the image alt attributes, color contrast, and the page title as the previous code reviewer asked, but for the page title, you forgot to edit and add the lines of code you changed in your report. Kindly add the lines of code you changed as you did for the other 2 changes.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by glitcher255** [comment]
@leonardodiasb nitpicked review, but done as asked.

**Review by amejid — APPROVED** [review]
Hi @SFarida, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- Correct use of Github flow ✔️ 
- Linter checks passing ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
